### ISSUE TITLE
Musicote

### ISSUE THREAD

**Issue by alex97ortega** [borjacano97/Serious-Train#14]
Molaría que cuando enseñásemos el juego ya tuviéramos una música chula, al menos para el gameplay. Hay que ver qué código necesitamos exactamente, y esperemos que no sea tanto lío como poner texto. En TPV dimos algo de ello, quien se encargue de esta issue puede empezar a trastear con ello por ahí.

**Comment by RoberInside** [comment]
esto puedo verlo yo pero ya lo hablamos mañana
