### ISSUE TITLE
Implementar vida a los enemigos

### ISSUE THREAD

**Issue by borjacano97** [borjacano97/Serious-Train#5]
Hay que implementar el sistema de daños, actualmente los enemigos se mueren por contacto. Para ello es necesario:

-  Dotar a los enemigos de una vida y armadura específico a su subclase (tipo de zombie)
-  Hay que hacer que las balas tengan un valor de daño determinado dependiendo de su tipo (tipo de arma)
- Implementar una forma de que un enemigo sepa qué tipo de bala le ha colisionado y restarse vida en consecuencia

**Comment by Filinouns** [comment]
Got it
