### ISSUE TITLE
Tienda

### ISSUE THREAD

**Issue by alex97ortega** [borjacano97/Serious-Train#7]
A ver quien tiene narices de empezar con esta maravilla

**Comment by Filinouns** [comment]
Caracteristicas de tienda:
- Dinero (que el player obtenga dinero, tanto por superar un nivel como por enemigos)
- Menu inicial de tienda, opciones: Menu Vagones, Menu Armas, Menu Npcs y Boton Siguiente nivel
- Menu Vagones con las caracteristicas del gdd (ademas de boton "atras")
       Se deberian poder elegir diferentes vagones, que se vea su descripcion, caracteristicas y subir de nivel/comprar. Ademas de un sistema de seleccion de vagones (poner y quitar vagones del tren "gdd")
- Menu Armas con las caracteristicas del gdd (ademas de boton "atras")
       Eleccion entre diferentes armas (pistola, metralleta, escopeta, bazooka y "extra"), cada una con su descripcion, caracteristicas y posibles mejoras.
- Menu Npcs con las caracteristicas del gdd (ademas de boton "atras")
       Visualizacion de los Npcs que te acompañan, cada uno con sus caracteristicas, descripcion, posicion en el tren (no modificable) y posibles mejoras.

**Comment by alex97ortega** [comment]
Lo que habría que hacer por pasos es lo siguiente (cada punto puede ser una tarea o issue):
1. Crear instancia tienda que herede de estado y asignarle los atributos y demás valores para objetos, dinero, etc. (opino que estaría bien un vector de objetos bloqueados y otro de desbloqueados, y si son muchos dividirlos en vector de vagones y armas tambien)
2. Colocar un fondo, ya sea estandar o hecho guay, y diferenciar la zona de vagones a la de armas como dijo Andrés), yo creo que es más coñazo hacer dos pantallas, se dividen en dos partes y listo. 
3. Conseguir que la tienda se muestre después de cada nivel y crear un botón que pase al siguiente nivel, tambien que se muestren el dinero correctamente (para ello necesitamos haber solucionado el issue del texto). No se si lo sabéis pero los puntos del dinero ya están implementados, hay una variable global que los acumula dependiendo del tipo de enemigo (aun no está lo de la distancia con el tren), solo falta que se muestren en pantalla, solo se pueden ver de momento con el cout.
4. Elegir si primero se implementará el desbloqueo de armas o el de vagones, en verdad da igual, van a ser casi identicos, lo unico que cambia es que para los vagones necesitamos una imagen del tren donde se vayan "colocando" las posiciones de los vagones (esto se hace más adelante) mientras que el arma es sólo cambiar una cosa, así que mejor empezar por ésta.
5. Implementar un arma que esté bloqueada a parte de la original que ya se tiene, y ser capaz de poder desbloquearse y usarse al nivel siguiente, ya sea comprándose (habiendo gastado el dinero correctamente) o automáticamente al pasar el nivel X, opino que estaría bien hacer un arma distinta para cada desbloqueo para ver si funcionan ambas con distintas instancias. Debería de haber un icono que mostrara el arma elegida, clickeada.
6. Hacer lo mismo pa los vagones, mostrándose el tren. Para que sea más fácil, hagámoslo sin arrastrar, simplemente el primer vagón que se clickee ocupará la posición 1, el segundo 2, etc. Para ello tendrá que haber un botón de deshacer.
7. Ponerlo bonico, añadiendo texto que diga lo que hace cada uno, poniendo el sprite negro si está bloqueado, conseguir subir y bajar la lista (ya que ni de coña se podrán ver todos los accesorios en pantalla a la vez), etc.
Esto ultimo que parece chungo sigue el mismo principio que el de las animaciones, si la imagen de la lista tiene 500 pix de alto, se muestran en pantalla 200 y con cierto botón o tecla se desplaza la proporción mostrada hacia abajo. Puede que lo chungo vaya a ser como diferenciar el bajar una lista u otra si las dos se muestran a la vez, pero como tenemos ya un método que nos indica la pos del mouse, yo creo que no va a haber problema.
8. Si hemos conseguido hacer esto somos los putos amos, debería ser fácil liarse a meter más vagones y armas

**Comment by alex97ortega** [comment]
Aun no he puesto nada de los Npcs porque no está decidido como va a ir, pero yo creo que se podrá dividir en tres columnas

**Comment by RoberInside** [comment]
50 % de la tienda para el hito 2
