### ISSUE TITLE
HUD

### ISSUE THREAD

**Issue by alex97ortega** [borjacano97/Serious-Train#9]
Seguramente haya que preguntar a Carlos, porque me puse con ello una tarde y me ponía que había que añadir librerías maravillosas y eso es un coñazo. Si encontráis algo más simple bienvenido sea

**Comment by RoberInside** [comment]
hud no?

**Comment by alex97ortega** [comment]
Si, pero hay una librería especifica para mostrar texto (SDL_ttf) que no tenemos, el código es muy simple y se maneja bien desde el proyect pero no consigo introducir bien la librería, creo que dejé comentado en la constructora de Play como era para poner texto, son 4 lineas

**Comment by gonguz** [comment]
Supuestamente, el texto debería aparecer. El problema es que al final borramos la rama que tenía incluidas las librerías mixer y ttf, y no encuentro como se hace. Por tanto no he podido realizar la tarea al 100%.

**Comment by gonguz** [comment]
Ya aparece el texto, hay que cambairlo de estado, actualizarlo(ya se como) y cambiar la fuente, la que hay ahora. Por cierto, no hemos decidido ni siquiera estética de de menús, botones, ni fuentes. Habría que hacerlo ya, el tiempo vuela, y son cosas que ayudan para que nuestro juego tenga algo visible, aparte de personajes, etc.
